Repository openwhale/spritz, pull requests merged in 2018-04, with the labels that each got.

#14 enforce styling using checkstyle
  checkstyle.xml
  pom.xml
  src/main/java/com/github/boyeborg/spritz/Main.java
Labels: chore

#16 developer and contributor sections in the pom-file
  pom.xml
Labels: chore

#24 improve tab support in checkstyle configuration
  checkstyle.xml
Labels: chore

#26 Add pull request template
  .github/pull_request_template.md
Labels: doc

#31 create mvp solution
  .vscode/settings.json
  src/main/java/com/github/boyeborg/spritz/Batch.java
  src/main/java/com/github/boyeborg/spritz/CollectorFactory.java
  src/main/java/com/github/boyeborg/spritz/EventConsumer.java
  src/main/java/com/github/boyeborg/spritz/ICollector.java
  src/main/java/com/github/boyeborg/spritz/Main.java
  src/test/java/com/github/boyeborg/spritz/SampleTest.java
Labels: twist

#33 add missing information from docstrings
  src/main/java/com/github/boyeborg/spritz/EventConsumer.java
  src/main/java/com/github/boyeborg/spritz/ICollector.java
Labels: bug

#35 update badges to match the new url
  README.md
Labels: doc

#43 add support for naming the collectors
  src/main/java/com/github/boyeborg/spritz/CollectorFactory.java
Labels: twist

#44 output headers when calling `toString` on the event consumer
  src/main/java/com/github/boyeborg/spritz/EventConsumer.java
Labels: twist

#46 update version to 0.2
  pom.xml
Labels: chore

#47 remove all references to old repo
  .vscode/launch.json
  src/main/java/com/github/openwhale/spritz/Batch.java
  src/main/java/com/github/openwhale/spritz/CollectorFactory.java
  src/main/java/com/github/openwhale/spritz/EventConsumer.java
  src/main/java/com/github/openwhale/spritz/ICollector.java
  src/test/java/com/github/openwhale/spritz/SampleTest.java
Labels: bug

#50 add multithread support for batches
  src/main/java/com/github/openwhale/spritz/Batch.java
  src/main/java/com/github/openwhale/spritz/EventConsumer.java
Labels: twist
